name: Check that PRs are set to alpha

on:
  pull_request_target:
   types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: master
          exclude: alpha # Don't prevent going from develop -> master
          change-to: alpha
          comment: |
            Your PR was set to `master` but as our [Contributing Guidelines](https://github.com/BrycensRanch/TownyPlus/blob/master/CONTRIBUTING.md) state, PRs should be sent to `alpha`
            The base branch of this PR has been automatically changed to `alpha`, please check that there are no merge conflicts.
